[project]
name = "VectorCode"
dynamic = ["version"]
description = "A tool to vectorise repositories for RAG."
dependencies = ["chromadb<=0.6.3", "argcomplete>=3.5.3", "sentence-transformers>=3.3.1", "pathspec>=0.12.1", "tabulate>=0.9.0", "shtab>=1.7.1", "numpy>=2.2.1", "FlagEmbedding>=1.3.3"]
requires-python = "<3.13,>=3.11"
readme = "README.md"

[[project.authors]]
name = "Davidyz"
email = "hzjlyz@gmail.com"

[project.license]
text = "MIT"

[project.scripts]
vectorcode = "vectorcode.main:main"

[project.optional-dependencies]
dev = ["ipython>=8.31.0", "ruff>=0.9.1", "viztracer>=1.0.0", "pre-commit>=4.0.1", "pytest>=8.3.4"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "file"
path = "./src/vectorcode/__init__.py"
